version: "3.8"

services:
  # FastAPI 서버
  fastapi:
    image: python:3.10-slim
    container_name: fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./wait-for-it.sh:/wait-for-it.sh
    working_dir: /app
    command: >
      sh -c "./wait-for-it.sh mysql:3306 -- 
             apt-get update && 
             apt-get install -y libgl1 libglib2.0-0 libmariadb-dev gcc pkg-config && 
             pip install --no-cache-dir -r requirements.txt && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
#    environment:
#      - BROKER_URL=amqp://guest:guest@rabbitmq//
#      - DATABASE_URL=mysql+pymysql://techeer:techeer20250201@mysql:3306/focus_db
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mysql

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP 포트
      - "15672:15672"  # RabbitMQ 관리 콘솔 포트

  # MySQL DB
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    # environment:
    #   MYSQL_ROOT_PASSWORD: root_password
    #   MYSQL_DATABASE: focus_db
    #   MYSQL_USER: techeer
    #   MYSQL_PASSWORD: techeer20250201
    env_file:
      - .env

  # Celery 워커
  celery:
    image: python:3.10-slim
    container_name: celery_worker
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "apt-get update &&
             apt-get install -y libgl1 libglib2.0-0 libmariadb-dev gcc pkg-config &&
             pip install --no-cache-dir -r requirements.txt &&
             celery -A app.celery_app worker --loglevel=info"
    #    environment:
#      - BROKER_URL=amqp://guest:guest@rabbitmq//
#      - RESULT_BACKEND=db+mysql://celery_user:celery_password@mysql/celery_db
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env

    depends_on:
      - rabbitmq
      - mysql
